on:
  push:
    branches:
      -master
  schedule:
    - cron: 0 */12 * * *
    # 每隔12小时
  workflow_dispatch: # on button click
jobs:
  update_external_airflow_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN   }} # 令牌
          upstream_repository: feverrun/my_scripts  # 上游仓库
          target_repository: kingmacth/my_scripts  # 你要推送的仓库
          upstream_branch: main  # 默认是拉取上游仓库的master分支
          target_branch: master  # 默认推送到你的仓库master分支
          force: true  # 是否强制推送
          tags: true  # 确定是否使用-tags
